### ISSUE TITLE
[要望] mono 5.x系へのアップグレード

### ISSUE THREAD

**Issue by SC-MAKERS** [exKAZUu/ai-container#48]
こんにちは。コンテスト実行環境の構築ありがとうございます。

C#7製プログラムをコンパイルしたいので、
差し支えなければmonoを5.x系へアップグレードしていただけませんでしょうか。
https://www.mono-project.com/download/stable/#download-lin-ubuntu

お手数ですがよろしくご検討ください。

**Comment by exKAZUu** [comment]
@SC-MAKERS
ご要望をいただき、ありがとうございます。
Dockerスクリプトの更新は完了しましたが、本番環境への導入には少々時間がかかります。
導入作業が完了しましたら、またご連絡いたします。（今晩夜を予定しています。）

**Comment by SC-MAKERS** [comment]
@exKAZUu 早速のご対応ありがとうございます。
本番環境への導入の件、承知しました。引続きよろしくお願いいたします。

**Comment by exKAZUu** [comment]
@SC-MAKERS すみません、予定より遅れてしまいましたが、本番環境への導入が完了しました。
詳細なバージョン情報は https://github.com/exKAZUu/ai-container/blob/master/available_languages.md を御覧ください。

**Comment by SC-MAKERS** [comment]
@exKAZUu 本番環境にてC#7製プログラムがコンパイルできるようになったことを確認いたしました。
ご対応いただきありがとうございました。
