### ISSUE TITLE
[要望] cythonの追加

### ISSUE THREAD

**Issue by takedarts** [exKAZUu/ai-container#50]
実行環境の構築ありがとうございます。

python3を使ってプログラム開発をしているのですが、性能向上のためのcythonを使いたいと思っています。
問題がなければcythonをpython3の環境に追加してもらえないでしょうか。

ご検討、お願いいたします。

**Comment by exKAZUu** [comment]
@takedarts ご要望をいただき、ありがとうございます。金曜日中に本番環境へ導入予定です。
なお、Cythonの導入方法は #51 の通りですが、宜しかったでしょうか？

**Comment by takedarts** [comment]
@exKAZUu 対応くださり、ありがとうございます。
まだDocker環境では確認しておりませんが、localのubuntu環境では同じ構成で動作確認いたしました。
土曜日以降に、本番環境でも動作確認させていただきます。

**Comment by exKAZUu** [comment]
@takedarts 先程、本番環境を更新しました。環境の詳細な情報は以下を御覧ください。
https://github.com/exKAZUu/ai-container/blob/master/available_languages.md
